print('=== GUIA COMPLETO: RECEBIMENTO MANUAL DE NF-e (GRATUITO) ===')
print('')
print('📋 PASSO A PASSO PARA RECEBER NF-e:')
print('')
print('1️⃣ ACESSAR PORTAL SEFAZ-MS')
print('   URL: https://www.sefaz.ms.gov.br/')
print('   • Use certificado digital A1 ou A3')
print('   • Vá em "NF-e" > "Consultar NF-e"')
print('')
print('2️⃣ CONSULTAR NF-e RECEBIDAS')
print('   • Filtrar por período (últimos 30 dias recomendado)')
print('   • Buscar por CPF/CNPJ da propriedade')
print('   • Selecionar as notas desejadas')
print('')
print('3️⃣ BAIXAR XMLs')
print('   • Para cada NF-e, clicar em "Download XML"')
print('   • Salvar os arquivos .xml no computador')
print('   • IMPORTANTE: Baixar apenas XMLs válidos')
print('')
print('4️⃣ UPLOAD NO MONPEC')
print('   • Acesse: /propriedade/{ID}/compras/nota-fiscal/upload/')
print('   • Selecione e envie cada arquivo XML')
print('   • Sistema processa automaticamente')
print('')
print('5️⃣ VERIFICAR RESULTADO')
print('   • NF-e aparece em Compras > Notas Fiscais')
print('   • Produtos cadastrados automaticamente')
print('   • Conta a pagar gerada')
print('   • Ordem de compra vinculada (se existir)')
print('')
print('🔄 FREQUÊNCIA RECOMENDADA:')
print('   • Diariamente ou semanalmente')
print('   • Depende do volume de compras')
print('   • Não precisa ser em tempo real')
print('')
print('🎯 VANTAGENS DO MÉTODO MANUAL:')
print('   ✅ 100% GRATUITO (não paga APIs)')
print('   ✅ Dados oficiais diretamente da SEFAZ')
print('   ✅ Controle total sobre o que importar')
print('   ✅ Funciona mesmo sem internet')
print('   ✅ Backup automático dos XMLs')
print('')
print('⚠️ DICAS IMPORTANTES:')
print('   • Sempre baixe o XML original da SEFAZ')
print('   • Não use XMLs de terceiros (podem estar alterados)')
print('   • Verifique se o XML está íntegro antes do upload')
print('   • Faça backup dos XMLs em local seguro')