# Generated by Django 4.2.7 on 2025-10-17 13:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Animal',
                'verbose_name_plural': 'Categorias de Animais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Cultura')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produtor')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Produtor Rural',
                'verbose_name_plural': 'Produtores Rurais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=200, verbose_name='Nome da Propriedade')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('area_total_ha', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área Total (ha)')),
                ('tipo_operacao', models.CharField(choices=[('PECUARIA', 'Pecuária'), ('AGRICULTURA', 'Agricultura'), ('MISTA', 'Mista')], max_length=20, verbose_name='Tipo de Operação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.produtorrural', verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome_propriedade'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosProjecaoRebanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_natalidade_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taxa de Natalidade Anual (%)')),
                ('taxa_mortalidade_bezerros_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taxa de Mortalidade de Bezerros Anual (%)')),
                ('taxa_mortalidade_adultos_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taxa de Mortalidade de Adultos Anual (%)')),
                ('percentual_venda_machos_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual de Venda de Machos Anual (%)')),
                ('percentual_venda_femeas_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual de Venda de Fêmeas Anual (%)')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20, verbose_name='Periodicidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('propriedade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Parâmetros de Projeção do Rebanho',
                'verbose_name_plural': 'Parâmetros de Projeção do Rebanho',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoProjetada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(verbose_name='Data da Movimentação')),
                ('tipo_movimentacao', models.CharField(choices=[('NASCIMENTO', 'Nascimento'), ('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('MORTE', 'Morte'), ('TRANSFERENCIA_ENTRADA', 'Transferência de Entrada'), ('TRANSFERENCIA_SAIDA', 'Transferência de Saída')], max_length=25, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaanimal', verbose_name='Categoria')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Movimentação Projetada',
                'verbose_name_plural': 'Movimentações Projetadas',
                'ordering': ['data_movimentacao', 'categoria'],
            },
        ),
        migrations.CreateModel(
            name='CicloProducaoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safra', models.CharField(max_length=20, verbose_name='Safra (ex: 2025/2026)')),
                ('area_plantada_ha', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área Plantada (ha)')),
                ('produtividade_esperada_sc_ha', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Produtividade Esperada (sc/ha)')),
                ('custo_producao_por_ha', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo de Produção por ha (R$)')),
                ('preco_venda_por_sc', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda por sc (R$)')),
                ('data_inicio_plantio', models.DateField(verbose_name='Data de Início do Plantio')),
                ('data_fim_colheita', models.DateField(verbose_name='Data de Fim da Colheita')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.cultura', verbose_name='Cultura')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Ciclo de Produção Agrícola',
                'verbose_name_plural': 'Ciclos de Produção Agrícola',
                'ordering': ['-data_inicio_plantio'],
            },
        ),
        migrations.CreateModel(
            name='RegraPromocaoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_minima_meses', models.PositiveIntegerField(verbose_name='Idade Mínima (meses)')),
                ('idade_maxima_meses', models.PositiveIntegerField(verbose_name='Idade Máxima (meses)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_destino', to='gestao_rural.categoriaanimal', verbose_name='Categoria de Destino')),
                ('categoria_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_origem', to='gestao_rural.categoriaanimal', verbose_name='Categoria de Origem')),
            ],
            options={
                'verbose_name': 'Regra de Promoção de Categoria',
                'verbose_name_plural': 'Regras de Promoção de Categoria',
                'unique_together': {('categoria_origem', 'categoria_destino')},
            },
        ),
        migrations.CreateModel(
            name='InventarioRebanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_inventario', models.DateField(verbose_name='Data do Inventário')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaanimal', verbose_name='Categoria')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Inventário do Rebanho',
                'verbose_name_plural': 'Inventários do Rebanho',
                'ordering': ['-data_inventario', 'categoria'],
                'unique_together': {('propriedade', 'categoria', 'data_inventario')},
            },
        ),
    ]
