# Generated by Django 4.2.7 on 2025-10-17 13:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='car',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CAR'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='incra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='INCRA'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='nirf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIRF'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='tipo_propriedade',
            field=models.CharField(choices=[('PROPRIA', 'Própria'), ('ARRENDAMENTO', 'Arrendamento')], default='PROPRIA', max_length=20, verbose_name='Tipo de Propriedade'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='valor_hectare_proprio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor por Hectare (R$)'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='valor_mensal_hectare_arrendamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Mensal por Hectare (R$)'),
        ),
    ]
