# Generated by Django 4.2.7 on 2025-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0002_propriedade_car_propriedade_incra_propriedade_nirf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtorrural',
            name='anos_experiencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anos de Experiência na Atividade'),
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='documento_identidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento de Identidade (RG)'),
        ),
    ]
