# Generated by Django 4.2.7 on 2025-10-17 13:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0003_produtorrural_anos_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosprojecaorebanho',
            name='percentual_venda_femeas_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual de Venda de Fêmeas Anual (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosprojecaorebanho',
            name='percentual_venda_machos_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual de Venda de Machos Anual (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosprojecaorebanho',
            name='taxa_mortalidade_adultos_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taxa de Mortalidade de Adultos Anual (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosprojecaorebanho',
            name='taxa_mortalidade_bezerros_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taxa de Mortalidade de Bezerros Anual (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosprojecaorebanho',
            name='taxa_natalidade_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taxa de Natalidade Anual (%)'),
        ),
    ]
