# Generated by Django 4.2.7 on 2025-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0004_alter_parametrosprojecaorebanho_percentual_venda_femeas_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='tipo_ciclo_pecuario',
            field=models.CharField(blank=True, choices=[('CRIA', 'Cria'), ('RECRIA', 'Recria'), ('ENGORDA', 'Engorda'), ('CICLO_COMPLETO', 'Ciclo Completo')], max_length=20, null=True, verbose_name='Tipo de Ciclo Pecuário'),
        ),
    ]
