# Generated by Django 4.2.7 on 2025-10-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0005_propriedade_tipo_ciclo_pecuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_transferencia', models.DateField(verbose_name='Data da Transferência')),
                ('tipo_transferencia', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de Transferência')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaanimal', verbose_name='Categoria')),
                ('propriedade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='gestao_rural.propriedade', verbose_name='Propriedade de Destino')),
                ('propriedade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='gestao_rural.propriedade', verbose_name='Propriedade de Origem')),
            ],
            options={
                'verbose_name': 'Transferência entre Propriedades',
                'verbose_name_plural': 'Transferências entre Propriedades',
                'ordering': ['-data_transferencia'],
            },
        ),
    ]
