# Generated by Django 4.2.7 on 2025-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0006_transferenciapropriedade'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaanimal',
            name='idade_maxima_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade Máxima (meses)'),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='idade_minima_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade Mínima (meses)'),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('I', 'Indefinido')], default='I', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='inventariorebanho',
            name='valor_por_cabeca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor por Cabeça (R$)'),
        ),
    ]
