# Generated by Django 4.2.7 on 2026-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0006_abastecimentocombustivel_ajusteorcamentocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtorrural',
            name='certificado_tipo',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Arquivo'), ('A3', 'A3 - Token/Cartão'), ('WINDOWS_STORE', 'Windows Certificate Store')], default='A1', help_text='A1: arquivo .p12/.pfx | A3: token/cartão físico | WINDOWS_STORE: certificado instalado no Windows', max_length=20, null=True, verbose_name='Tipo de Certificado'),
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='certificado_emissor',
            field=models.CharField(blank=True, help_text='Autoridade certificadora que emitiu o certificado', max_length=255, null=True, verbose_name='Emissor do Certificado'),
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='certificado_thumbprint',
            field=models.CharField(blank=True, help_text='Thumbprint do certificado no Windows Certificate Store (para certificados instalados)', max_length=40, null=True, verbose_name='Thumbprint do Certificado'),
        ),
    ]
