# Generated by Django 4.2.7 on 2025-10-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0007_categoriaanimal_idade_maxima_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaanimal',
            name='raca',
            field=models.CharField(choices=[('NELORE', 'Nelore'), ('ANGUS', 'Angus'), ('HEREFORD', 'Hereford'), ('BRAHMAN', 'Brahman'), ('SIMENTAL', 'Simental'), ('GIR', 'Gir'), ('GUZERA', 'Guzerá'), ('CANCHIM', 'Canchim'), ('SENEPOL', 'Senepol'), ('OUTROS', 'Outros')], default='NELORE', max_length=20, verbose_name='Raça'),
        ),
    ]
