# Generated by Django 4.2.7 on 2025-10-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0008_categoriaanimal_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia_venda', models.CharField(choices=[('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('quantidade_venda', models.PositiveIntegerField()),
                ('tipo_reposicao', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('COMPRA', 'Compra')], max_length=20)),
                ('quantidade_transferencia', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_compra', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_animal_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_animal_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_compra', to='gestao_rural.categoriaanimal')),
                ('categoria_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_venda', to='gestao_rural.categoriaanimal')),
                ('fazenda_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem_config', to='gestao_rural.propriedade')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_venda', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Configuração de Venda',
                'verbose_name_plural': 'Configurações de Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
