# Generated by Django 4.2.7 on 2025-10-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0009_configuracaovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaanimal',
            name='peso_medio_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso médio do animal nesta categoria em quilogramas', max_digits=8, null=True, verbose_name='Peso Médio (kg)'),
        ),
    ]
