# Generated by Django 4.2.7 on 2025-10-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0010_categoriaanimal_peso_medio_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaovenda',
            options={},
        ),
        migrations.CreateModel(
            name='CustoVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_custo', models.CharField(max_length=200, verbose_name='Nome do Custo')),
                ('tipo_custo', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('SANEAMENTO', 'Sanidade'), ('REPRODUCAO', 'Reprodução'), ('MANEJO', 'Manejo'), ('TRANSPORTE', 'Transporte'), ('ENERGIA', 'Energia e Combustível'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Custo')),
                ('valor_por_cabeca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Cabeça (R$)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_variaveis', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Custo Variável',
                'verbose_name_plural': 'Custos Variáveis',
                'ordering': ['tipo_custo', 'nome_custo'],
            },
        ),
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_custo', models.CharField(max_length=200, verbose_name='Nome do Custo')),
                ('tipo_custo', models.CharField(choices=[('MAQUINARIO', 'Maquinário e Equipamentos'), ('INFRAESTRUTURA', 'Infraestrutura'), ('PESSOAL', 'Pessoal'), ('ADMINISTRATIVO', 'Administrativo'), ('FINANCEIRO', 'Financeiro'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Custo')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Mensal (R$)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_fixos', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Custo Fixo',
                'verbose_name_plural': 'Custos Fixos',
                'ordering': ['tipo_custo', 'nome_custo'],
            },
        ),
        migrations.CreateModel(
            name='FluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('receita_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita Total (R$)')),
                ('custo_fixo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Fixo Total (R$)')),
                ('custo_variavel_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Variável Total (R$)')),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Bruto (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_caixa', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxos de Caixa',
                'ordering': ['-data_referencia'],
                'unique_together': {('propriedade', 'data_referencia')},
            },
        ),
    ]
