# Generated by Django 4.2.7 on 2025-10-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0012_custofixo_data_fim_custofixo_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custovariavel',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='custovariavel',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='custovariavel',
            name='meses_aplicaveis',
            field=models.JSONField(blank=True, default=list, verbose_name='Meses Aplicáveis'),
        ),
        migrations.AddField(
            model_name='custovariavel',
            name='tipo_periodo',
            field=models.CharField(choices=[('MENSAL', 'Mensal (todos os meses)'), ('PERIODO_ESPECIFICO', 'Período específico'), ('MESES_ESPECIFICOS', 'Meses específicos')], default='MENSAL', max_length=20, verbose_name='Tipo de Período'),
        ),
    ]
