# Generated by Django 4.2.7 on 2025-10-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0013_custovariavel_data_fim_custovariavel_data_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImobilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('vida_util_anos', models.IntegerField(verbose_name='Vida Útil (anos)')),
                ('taxa_depreciacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Depreciação (%)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Imobilizado',
                'verbose_name_plural': 'Categorias de Imobilizados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Financiamento',
                'verbose_name_plural': 'Tipos de Financiamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='meses_aplicaveis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Meses Aplicáveis'),
        ),
        migrations.AlterField(
            model_name='custovariavel',
            name='meses_aplicaveis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Meses Aplicáveis'),
        ),
        migrations.CreateModel(
            name='IndicadorFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Indicador')),
                ('tipo', models.CharField(choices=[('LIQUIDEZ', 'Liquidez'), ('RENTABILIDADE', 'Rentabilidade'), ('ENDIVIDAMENTO', 'Endividamento'), ('EFICIENCIA', 'Eficiência'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Indicador')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor do Indicador')),
                ('unidade', models.CharField(default='%', max_length=50, verbose_name='Unidade')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Indicador Financeiro',
                'verbose_name_plural': 'Indicadores Financeiros',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Financiamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Principal (R$)')),
                ('taxa_juros_anual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros Anual (%)')),
                ('tipo_taxa', models.CharField(choices=[('FIXA', 'Taxa Fixa'), ('VARIAVEL', 'Taxa Variável'), ('MISTA', 'Taxa Mista')], default='FIXA', max_length=20, verbose_name='Tipo de Taxa')),
                ('data_contratacao', models.DateField(verbose_name='Data de Contratação')),
                ('data_primeiro_vencimento', models.DateField(verbose_name='Data do Primeiro Vencimento')),
                ('data_ultimo_vencimento', models.DateField(verbose_name='Data do Último Vencimento')),
                ('numero_parcelas', models.IntegerField(verbose_name='Número de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiamentos', to='gestao_rural.propriedade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.tipofinanciamento', verbose_name='Tipo de Financiamento')),
            ],
            options={
                'verbose_name': 'Financiamento',
                'verbose_name_plural': 'Financiamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BemImobilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Bem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Aquisição (R$)')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Residual (R$)')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('data_inicio_depreciacao', models.DateField(verbose_name='Data de Início da Depreciação')),
                ('tipo_aquisicao', models.CharField(choices=[('COMPRA', 'Compra'), ('DOACAO', 'Doação'), ('HERANCA', 'Herança'), ('CONSTRUCAO', 'Construção Própria'), ('OUTROS', 'Outros')], default='COMPRA', max_length=20, verbose_name='Tipo de Aquisição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaimobilizado', verbose_name='Categoria')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens_imobilizados', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Bem Imobilizado',
                'verbose_name_plural': 'Bens Imobilizados',
                'ordering': ['nome'],
            },
        ),
    ]
