# Generated by Django 4.2.7 on 2025-10-17 21:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0014_categoriaimobilizado_tipofinanciamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosVendaPorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_venda_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual de Venda Anual (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaanimal', verbose_name='Categoria')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Parâmetro de Venda por Categoria',
                'verbose_name_plural': 'Parâmetros de Venda por Categoria',
                'ordering': ['categoria'],
                'unique_together': {('propriedade', 'categoria')},
            },
        ),
    ]
