# Generated by Django 4.2.7 on 2025-10-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0015_parametrosvendaporcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaovenda',
            name='fazenda_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino_config', to='gestao_rural.propriedade'),
        ),
    ]
