# Generated by Django 4.2.7 on 2025-10-28 13:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0016_configuracaovenda_fazenda_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaovenda',
            name='tipo_reposicao',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=20),
        ),
        migrations.CreateModel(
            name='PoliticaVendasCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Percentual de Venda (%)')),
                ('quantidade_venda', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Venda')),
                ('reposicao_tipo', models.CharField(choices=[('NAO_REP', 'Não repor'), ('TRANSFERENCIA', 'Transferência'), ('COMPRA', 'Compra'), ('AMBOS', 'Transferência + Compra')], default='NAO_REP', max_length=20, verbose_name='Tipo de Reposição')),
                ('quantidade_transferir', models.PositiveIntegerField(default=0, verbose_name='Quantidade para Transferir')),
                ('quantidade_comprar', models.PositiveIntegerField(default=0, verbose_name='Quantidade para Comprar')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaanimal', verbose_name='Categoria')),
                ('origem_fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicas_vendas_origem', to='gestao_rural.propriedade', verbose_name='Fazenda de Origem')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Política de Vendas por Categoria',
                'verbose_name_plural': 'Políticas de Vendas por Categoria',
                'unique_together': {('propriedade', 'categoria')},
            },
        ),
    ]
