# Generated by Django 4.2.7 on 2025-10-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0017_create_politica_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoprojetada',
            name='valor_por_cabeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por Cabeça (R$)'),
        ),
        migrations.AddField(
            model_name='movimentacaoprojetada',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total (R$)'),
        ),
        migrations.AddField(
            model_name='politicavendascategoria',
            name='usar_valor_personalizado',
            field=models.BooleanField(default=False, verbose_name='Usar Valor Personalizado'),
        ),
        migrations.AddField(
            model_name='politicavendascategoria',
            name='valor_por_cabeca_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por Cabeça Personalizado (R$)'),
        ),
        migrations.CreateModel(
            name='SCRBancoCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(upload_to='scr/', verbose_name='Arquivo PDF do SCR')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_referencia_scr', models.DateField(verbose_name='Data de Referência do SCR')),
                ('status', models.CharField(choices=[('IMPORTADO', 'Importado'), ('PROCESSADO', 'Processado'), ('DISTRIBUIDO', 'Distribuído'), ('ERRO', 'Erro')], default='IMPORTADO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrs', to='gestao_rural.produtorrural')),
            ],
            options={
                'verbose_name': 'SCR Banco Central',
                'verbose_name_plural': 'SCRs Banco Central',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('tipo_projeto', models.CharField(choices=[('CUSTEIO', 'Custeio'), ('INVESTIMENTO', 'Investimento'), ('COMERCIALIZACAO', 'Comercialização'), ('REFINANCIAMENTO', 'Refinanciamento')], max_length=20, verbose_name='Tipo de Projeto')),
                ('banco_solicitado', models.CharField(max_length=200, verbose_name='Banco Solicitado')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Solicitado (R$)')),
                ('prazo_pagamento', models.PositiveIntegerField(verbose_name='Prazo de Pagamento (meses)')),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros (%)')),
                ('data_solicitacao', models.DateField(verbose_name='Data de Solicitação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Aprovado (R$)')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONTRATADO', 'Contratado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('arquivo_projeto', models.FileField(blank=True, null=True, upload_to='projetos/', verbose_name='Arquivo do Projeto')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_bancarios', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Projeto Bancário',
                'verbose_name_plural': 'Projetos Bancários',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PROJETO_TECNICO', 'Projeto Técnico'), ('LAUDO_AVALIACAO', 'Laudo de Avaliação'), ('CONTRATO', 'Contrato'), ('COMPROVANTE_RENDA', 'Comprovante de Renda'), ('DOCUMENTO_PROPRIEDADE', 'Documento da Propriedade'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Documento')),
                ('nome_documento', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to='projetos/documentos/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestao_rural.projetobancario')),
            ],
            options={
                'verbose_name': 'Documento de Projeto',
                'verbose_name_plural': 'Documentos de Projetos',
                'ordering': ['projeto', 'tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='DividaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=200, verbose_name='Nome do Banco')),
                ('status_divida', models.CharField(choices=[('A_VENCER', 'A Vencer'), ('VENCIDO', 'Vencido'), ('QUITADO', 'Quitado')], max_length=20, verbose_name='Status da Dívida')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total (R$)')),
                ('quantidade_contratos', models.PositiveIntegerField(verbose_name='Quantidade de Contratos')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('scr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='gestao_rural.scrbancocentral')),
            ],
            options={
                'verbose_name': 'Dívida por Banco',
                'verbose_name_plural': 'Dívidas por Banco',
                'ordering': ['banco', 'status_divida'],
            },
        ),
        migrations.CreateModel(
            name='ContratoDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, verbose_name='Número do Contrato')),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Contrato (R$)')),
                ('taxa_juros_anual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros Anual (%)')),
                ('quantidade_parcelas', models.PositiveIntegerField(verbose_name='Quantidade de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Parcela (R$)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('QUITADO', 'Quitado'), ('VENCIDO', 'Vencido'), ('RENEGOCIADO', 'Renegociado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('divida_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestao_rural.dividabanco')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_divida', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Contrato de Dívida',
                'verbose_name_plural': 'Contratos de Dívida',
                'ordering': ['propriedade', 'data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='AmortizacaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Principal (R$)')),
                ('valor_juros', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor dos Juros (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total (R$)')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Devedor (R$)')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Pago (R$)')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20, verbose_name='Status do Pagamento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizacoes', to='gestao_rural.contratodivida')),
            ],
            options={
                'verbose_name': 'Amortização de Contrato',
                'verbose_name_plural': 'Amortizações de Contratos',
                'ordering': ['contrato', 'numero_parcela'],
                'unique_together': {('contrato', 'numero_parcela')},
            },
        ),
    ]
