# Generated by Django 4.2.7 on 2025-11-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0020_tourosemen_alter_iatf_inseminador_protocoloiatf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iatf',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iatfs_veterinario_simples', to=settings.AUTH_USER_MODEL, verbose_name='Veterinário'),
        ),
    ]
