# Generated by Django 4.2.7 on 2025-11-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0023_curral_super_tela'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='curralevento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currallote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='curralsessao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('CHEQUE', 'Cheque'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão')], default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('pago', models.BooleanField(default=True, verbose_name='Pago/Recebido')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_rural.categoriafinanceira')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('INVESTIMENTO', 'Investimento')], default='CORRENTE', max_length=20, verbose_name='Tipo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
    ]
