# Generated by Django 4.2.7 on 2025-11-12 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0026_propriedade_ciclos_multiplos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Nome curto para identificar o manejo na agenda.', max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('data_prevista', models.DateField(blank=True, help_text='Data sugerida para execução do manejo.', null=True, verbose_name='Data prevista')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Informações extras específicas do manejo.', verbose_name='Metadados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Manejo',
                'verbose_name_plural': 'Manejos',
                'ordering': ['-data_prevista', '-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='animalindividual',
            name='codigo_eletronico',
            field=models.CharField(blank=True, help_text='Identificador eletrônico (RFID/EID)', max_length=50, null=True, unique=True, verbose_name='Código Eletrônico'),
        ),
        migrations.CreateModel(
            name='ManejoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('REPRODUTIVO', 'Reprodutivo'), ('SANITARIO', 'Sanitário'), ('NUTRICIONAL', 'Nutricional'), ('OPERACIONAL', 'Operacional'), ('COMERCIAL', 'Comercial'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('instrucoes', models.TextField(blank=True, help_text='Orientações padrão para execução deste manejo.', verbose_name='Instruções Gerais')),
                ('exige_registro_financeiro', models.BooleanField(default=False, help_text='Quando marcado, o manejo solicitará lançamento financeiro relacionado.', verbose_name='Exige vínculo financeiro')),
                ('cor_identificacao', models.CharField(default='#0d6efd', help_text='Cor hexadecimal utilizada em etiquetas e cards.', max_length=20, verbose_name='Cor de identificação')),
                ('tempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tempo estimado (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Manejo',
                'verbose_name_plural': 'Tipos de Manejo',
                'ordering': ['categoria', 'nome'],
                'unique_together': {('nome', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ManejoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=15, null=True, verbose_name='Status anterior')),
                ('status_novo', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], max_length=15, verbose_name='Status novo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_evento', models.DateTimeField(auto_now_add=True, verbose_name='Data do evento')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='gestao_rural.manejo', verbose_name='Manejo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Manejo',
                'verbose_name_plural': 'Históricos de Manejo',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='ManejoChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('exige_anexo', models.BooleanField(default=False, help_text='Solicita documento ou foto comprobatória para conclusão.', verbose_name='Exige anexo')),
                ('tipo_manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='gestao_rural.manejotipo', verbose_name='Tipo de Manejo')),
            ],
            options={
                'verbose_name': 'Item de Checklist de Manejo',
                'verbose_name_plural': 'Itens de Checklist de Manejo',
                'ordering': ['tipo_manejo', 'ordem', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='manejo',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Opcional. Utilize quando o manejo é específico para um animal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='gestao_rural.animalindividual', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='gestao_rural.propriedade', verbose_name='Propriedade'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manejos', to='gestao_rural.manejotipo', verbose_name='Tipo de Manejo'),
        ),
        migrations.CreateModel(
            name='ManejoChecklistExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em progresso'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='gestao_rural.manejochecklistitem', verbose_name='Item')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_execucoes', to='gestao_rural.manejo', verbose_name='Manejo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Execução de Checklist de Manejo',
                'verbose_name_plural': 'Execuções de Checklist de Manejo',
                'ordering': ['manejo', 'item__ordem'],
                'unique_together': {('manejo', 'item')},
            },
        ),
    ]
