# Generated by Django 4.2.7 on 2025-11-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0027_manejo_alter_animalindividual_codigo_eletronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejotipo',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações adicionais (tags, botões, cores específicas).', verbose_name='Metadados'),
        ),
        migrations.AddField(
            model_name='manejotipo',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para integrações (ex.: rep_programar_iatf).', max_length=120, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
