# Generated by Django 4.2.7 on 2025-11-12 19:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0028_manejotipo_metadados_manejotipo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteiatf',
            name='categoria_animais',
            field=models.ManyToManyField(blank=True, help_text='Categorias de animais incluídas neste lote (ex.: Matrizes, Novilhas).', related_name='lotes_iatf', to='gestao_rural.categoriaanimal', verbose_name='Categorias de Vacas'),
        ),
        migrations.AddField(
            model_name='loteiatf',
            name='inseminador_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_iatf_inseminador', to=settings.AUTH_USER_MODEL, verbose_name='Inseminador Padrão'),
        ),
        migrations.AddField(
            model_name='loteiatf',
            name='score_reprodutivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avaliação geral do lote antes do protocolo (0 a 100%).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Score Reprodutivo (%)'),
        ),
        migrations.CreateModel(
            name='EtapaLoteIATF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(max_length=150, verbose_name='Nome da Etapa')),
                ('codigo_etapa', models.CharField(blank=True, help_text='Identificador curto (ex.: D0, D8, D10).', max_length=60, null=True, verbose_name='Código da Etapa')),
                ('dia_relativo', models.IntegerField(help_text='Dia em relação ao início do protocolo (Ex.: 0, 8, 10).', verbose_name='Dia Relativo')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('hora_prevista', models.TimeField(blank=True, null=True, verbose_name='Horário Previsto')),
                ('medicamento_planejado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicamento Planejado')),
                ('descricao_planejada', models.TextField(blank=True, null=True, verbose_name='Descrição / Procedimentos')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADA', 'Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_execucao', models.DateField(blank=True, null=True, verbose_name='Data de Execução')),
                ('hora_execucao', models.TimeField(blank=True, null=True, verbose_name='Hora de Execução')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('inseminador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_iatf_inseminador', to=settings.AUTH_USER_MODEL, verbose_name='Inseminador')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='gestao_rural.loteiatf', verbose_name='Lote IATF')),
                ('responsavel_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_iatf_executadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Execução')),
                ('responsavel_planejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_iatf_planejadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Planejado')),
                ('touro_semen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_iatf', to='gestao_rural.tourosemen', verbose_name='Touro Utilizado')),
            ],
            options={
                'verbose_name': 'Etapa de Lote IATF',
                'verbose_name_plural': 'Etapas de Lote IATF',
                'ordering': ['lote', 'dia_relativo', 'data_prevista'],
            },
        ),
    ]
