# Generated by Django 4.2.7 on 2025-11-13 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0031_animais_complementares'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteCotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do destinatário')),
                ('token', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('RESPONDIDO', 'Respondido'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('observacao_resposta', models.TextField(blank=True, null=True, verbose_name='Observações do fornecedor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_cotacao_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_cotacao', to='gestao_rural.fornecedor', verbose_name='Fornecedor')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='gestao_rural.requisicaocompra', verbose_name='Requisição')),
            ],
            options={
                'ordering': ['-criado_em'],
                'verbose_name': 'Convite de Cotação',
                'verbose_name_plural': 'Convites de Cotação',
            },
        ),
        migrations.AddConstraint(
            model_name='convitecotacaofornecedor',
            constraint=models.UniqueConstraint(fields=('requisicao', 'fornecedor'), name='unique_convite_requisicao_fornecedor'),
        ),
    ]
