# Generated by Django 4.2.7 on 2025-11-13 16:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0035_assinaturas_stripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoCompraMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Limite Mensal (R$)')),
                ('limite_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Limite Extra (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Orçamento Mensal de Compras',
                'verbose_name_plural': 'Orçamentos Mensais de Compras',
                'ordering': ['-ano', '-mes', 'setor__nome'],
            },
        ),
        migrations.CreateModel(
            name='AjusteOrcamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Informe o valor adicional aprovado para este mês.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Ajuste (R$)')),
                ('justificativa', models.TextField(verbose_name='Justificativa do ajuste')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ajuste Emergencial de Orçamento',
                'verbose_name_plural': 'Ajustes Emergenciais de Orçamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='orcamentocompramensal',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compras_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamentocompramensal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compras_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamentocompramensal',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_compras', to='gestao_rural.propriedade', verbose_name='Propriedade'),
        ),
        migrations.AddField(
            model_name='orcamentocompramensal',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_mensais', to='gestao_rural.setorpropriedade', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='ajusteorcamentocompra',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_orcamento_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajusteorcamentocompra',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='gestao_rural.orcamentocompramensal', verbose_name='Orçamento'),
        ),
        migrations.AlterUniqueTogether(
            name='orcamentocompramensal',
            unique_together={('propriedade', 'setor', 'ano', 'mes')},
        ),
    ]
