# Generated by Django 4.2.7 on 2025-11-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0040_animalpesagem_campos_racao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centrocustofinanceiro',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='centrocustofinanceiro',
            name='propriedade',
        ),
        migrations.RemoveField(
            model_name='fechamentomensal',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='fechamentomensal',
            name='propriedade',
        ),
        migrations.RemoveField(
            model_name='parcelatitulo',
            name='conta_liquidacao',
        ),
        migrations.RemoveField(
            model_name='parcelatitulo',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='conta_preferencial',
        ),
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='plano_conta',
        ),
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='propriedade',
        ),
        migrations.RemoveField(
            model_name='transferenciafinanceira',
            name='conta_destino',
        ),
        migrations.RemoveField(
            model_name='transferenciafinanceira',
            name='conta_origem',
        ),
        migrations.RemoveField(
            model_name='transferenciafinanceira',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='transferenciafinanceira',
            name='movimento_destino',
        ),
        migrations.RemoveField(
            model_name='transferenciafinanceira',
            name='movimento_origem',
        ),
        migrations.RemoveField(
            model_name='transferenciafinanceira',
            name='propriedade',
        ),
        migrations.AlterModelOptions(
            name='centrocusto',
            options={'ordering': ['nome'], 'verbose_name': 'Centro de Custo', 'verbose_name_plural': 'Centros de Custo'},
        ),
        migrations.AlterModelOptions(
            name='planoconta',
            options={'ordering': ['codigo'], 'verbose_name': 'Plano de Conta', 'verbose_name_plural': 'Planos de Contas'},
        ),
        migrations.AlterModelOptions(
            name='setorpropriedade',
            options={'ordering': ['propriedade__nome_propriedade', 'nome'], 'verbose_name': 'Setor da Propriedade', 'verbose_name_plural': 'Setores da Propriedade'},
        ),
        migrations.RemoveConstraint(
            model_name='centrocusto',
            name='unique_centro_custo_por_propriedade_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='planoconta',
            name='unique_plano_conta_por_propriedade_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='setorpropriedade',
            name='unique_setor_por_propriedade_nome',
        ),
        migrations.RenameIndex(
            model_name='assinaturacliente',
            new_name='gestao_rura_stripe__628be9_idx',
            old_name='gestao_rura_stripe__c9bd88_idx',
        ),
        migrations.RenameIndex(
            model_name='assinaturacliente',
            new_name='gestao_rura_stripe__9724d3_idx',
            old_name='gestao_rura_stripe__5b5809_idx',
        ),
        migrations.RemoveField(
            model_name='movimentofinanceiro',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='movimentofinanceiro',
            name='propriedade',
        ),
        migrations.AddField(
            model_name='animalindividual',
            name='numero_manejo',
            field=models.CharField(blank=True, help_text='Número de manejo extraído do código SISBOV (6 dígitos para códigos de 15 dígitos)', max_length=20, null=True, verbose_name='Número de Manejo'),
        ),
        migrations.AlterField(
            model_name='animaldocumento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animalhistoricoevento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animalpesagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animalreproducaoevento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animaltratamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animalvacinaaplicada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo_financeiros', to='gestao_rural.propriedade'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='gestao_rural.centrocusto'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('TRANSFERENCIA', 'Transferência')], help_text='Preenchido automaticamente a partir da categoria.', max_length=15, verbose_name='Tipo do lançamento'),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='propriedade',
            field=models.ForeignKey(blank=True, help_text='Quando vazio, o plano fica disponível para todas as propriedades.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_conta', to='gestao_rural.propriedade'),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('TRANSFERENCIA', 'Transferência')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('propriedade', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='planoconta',
            unique_together={('propriedade', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='setorpropriedade',
            unique_together={('propriedade', 'nome')},
        ),
        migrations.AddIndex(
            model_name='animalhistoricoevento',
            index=models.Index(fields=['animal', 'data_evento'], name='gestao_rura_animal__a897dc_idx'),
        ),
        migrations.AddIndex(
            model_name='animalpesagem',
            index=models.Index(fields=['animal', 'data_pesagem'], name='gestao_rura_animal__dccb95_idx'),
        ),
        migrations.AddIndex(
            model_name='animalreproducaoevento',
            index=models.Index(fields=['animal', 'data_evento'], name='gestao_rura_animal__956329_idx'),
        ),
        migrations.AddIndex(
            model_name='animalreproducaoevento',
            index=models.Index(fields=['tipo_evento'], name='gestao_rura_tipo_ev_77a3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='animaltratamento',
            index=models.Index(fields=['animal', 'data_inicio'], name='gestao_rura_animal__68acaa_idx'),
        ),
        migrations.AddIndex(
            model_name='animalvacinaaplicada',
            index=models.Index(fields=['animal', 'data_aplicacao'], name='gestao_rura_animal__c2f59a_idx'),
        ),
        migrations.AddIndex(
            model_name='animalvacinaaplicada',
            index=models.Index(fields=['vacina'], name='gestao_rura_vacina_4d661f_idx'),
        ),
        migrations.DeleteModel(
            name='CentroCustoFinanceiro',
        ),
        migrations.DeleteModel(
            name='FechamentoMensal',
        ),
        migrations.DeleteModel(
            name='ParcelaTitulo',
        ),
        migrations.DeleteModel(
            name='TituloFinanceiro',
        ),
        migrations.DeleteModel(
            name='TransferenciaFinanceira',
        ),
        migrations.RemoveField(
            model_name='centrocusto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='planoconta',
            name='conta_pai',
        ),
        migrations.RemoveField(
            model_name='planoconta',
            name='ordem',
        ),
    ]
