# Generated by Django 4.2.7 on 2025-11-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0042_remover_agricultura'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('modulo', models.CharField(choices=[('PECUARIA', 'Pecuária'), ('FINANCEIRO', 'Financeiro'), ('NUTRICAO', 'Nutrição'), ('OPERACOES', 'Operações'), ('COMPRAS', 'Compras'), ('IATF', 'IATF'), ('RASTREABILIDADE', 'Rastreabilidade'), ('CONSOLIDADO', 'Consolidado')], max_length=50, verbose_name='Módulo')),
                ('configuracao', models.JSONField(default=dict, help_text='Configuração completa do template (campos, filtros, etc.)', verbose_name='Configuração')),
                ('template_html', models.TextField(blank=True, help_text='HTML do template', null=True, verbose_name='Template HTML')),
                ('publico', models.BooleanField(default=True, help_text='Se o template está disponível para todos', verbose_name='Público')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Relatório')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('modulo', models.CharField(choices=[('PECUARIA', 'Pecuária'), ('FINANCEIRO', 'Financeiro'), ('NUTRICAO', 'Nutrição'), ('OPERACOES', 'Operações'), ('COMPRAS', 'Compras'), ('IATF', 'IATF'), ('RASTREABILIDADE', 'Rastreabilidade'), ('CONSOLIDADO', 'Consolidado')], max_length=50, verbose_name='Módulo')),
                ('tipo_exportacao', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], default='HTML', max_length=10, verbose_name='Tipo de Exportação')),
                ('campos_selecionados', models.JSONField(default=list, help_text='Lista de campos que serão exibidos no relatório', verbose_name='Campos Selecionados')),
                ('filtros', models.JSONField(default=dict, help_text='Filtros aplicados ao relatório', verbose_name='Filtros')),
                ('agrupamentos', models.JSONField(default=list, help_text='Campos para agrupar os dados', verbose_name='Agrupamentos')),
                ('ordenacao', models.JSONField(default=list, help_text='Campos e direção de ordenação', verbose_name='Ordenação')),
                ('formatacao', models.JSONField(default=dict, help_text='Configurações de formatação (cores, estilos, etc.)', verbose_name='Formatação')),
                ('template_personalizado', models.TextField(blank=True, help_text='HTML customizado para o relatório (opcional)', null=True, verbose_name='Template Personalizado')),
                ('compartilhado', models.BooleanField(default=False, help_text='Se o relatório pode ser usado por outros usuários da propriedade', verbose_name='Compartilhado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('total_execucoes', models.PositiveIntegerField(default=0, verbose_name='Total de Execuções')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_customizados', to='gestao_rural.propriedade', verbose_name='Propriedade')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador')),
            ],
            options={
                'verbose_name': 'Relatório Customizado',
                'verbose_name_plural': 'Relatórios Customizados',
                'ordering': ['-data_atualizacao', 'nome'],
                'unique_together': {('propriedade', 'nome', 'usuario_criador')},
            },
        ),
    ]
