# Generated by Django 4.2.7 on 2025-11-18 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0043_templaterelatorio_relatoriocustomizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoassinatura',
            name='max_usuarios',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de usuários permitidos neste plano', verbose_name='Máximo de usuários'),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='modulos_disponiveis',
            field=models.JSONField(blank=True, default=list, help_text='Lista de módulos liberados para este plano', verbose_name='Módulos disponíveis'),
        ),
        migrations.CreateModel(
            name='TenantUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=150, verbose_name='Nome de exibição')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador'), ('VISUALIZADOR', 'Visualizador')], default='OPERADOR', max_length=20, verbose_name='Perfil')),
                ('modulos', models.JSONField(blank=True, default=list, help_text='Lista de módulos que este usuário pode acessar', verbose_name='Módulos liberados')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_tenant', to='gestao_rural.assinaturacliente', verbose_name='Assinatura')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário do Tenant',
                'verbose_name_plural': 'Usuários do Tenant',
                'ordering': ['nome_exibicao'],
                'unique_together': {('usuario', 'assinatura')},
            },
        ),
    ]
