# Generated by Django 4.2.7 on 2025-11-18 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0044_adicionar_tenant_usuario_e_campos_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('email_verificado', models.BooleanField(default=False, verbose_name='E-mail Verificado')),
                ('token_expira_em', models.DateTimeField(verbose_name='Token Expira em')),
                ('tentativas_verificacao', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_email', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Verificação de E-mail',
                'verbose_name_plural': 'Verificações de E-mail',
            },
        ),
        migrations.CreateModel(
            name='SessaoSegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Chave da Sessão')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_seguras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão Segura',
                'verbose_name_plural': 'Sessões Seguras',
                'ordering': ['-ultima_atividade'],
                'indexes': [models.Index(fields=['usuario', '-ultima_atividade'], name='gestao_rura_usuario_cc1a24_idx'), models.Index(fields=['ip_address', '-ultima_atividade'], name='gestao_rura_ip_addr_af65a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FALHA', 'Tentativa de Login Falha'), ('CRIAR_USUARIO', 'Criar Usuário'), ('EDITAR_USUARIO', 'Editar Usuário'), ('DESATIVAR_USUARIO', 'Desativar Usuário'), ('REATIVAR_USUARIO', 'Reativar Usuário'), ('ALTERAR_SENHA', 'Alterar Senha'), ('RECUPERAR_SENHA', 'Recuperar Senha'), ('CRIAR_ASSINATURA', 'Criar Assinatura'), ('ATUALIZAR_ASSINATURA', 'Atualizar Assinatura'), ('CANCELAR_ASSINATURA', 'Cancelar Assinatura'), ('PROCESSAR_PAGAMENTO', 'Processar Pagamento'), ('WEBHOOK_STRIPE', 'Webhook Stripe'), ('ACESSO_NAO_AUTORIZADO', 'Tentativa de Acesso Não Autorizado'), ('ALTERAR_PERMISSOES', 'Alterar Permissões')], max_length=50, verbose_name='Tipo de Ação')),
                ('nivel_severidade', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20, verbose_name='Nível de Severidade')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='Erro (se houver)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='gestao_rura_usuario_4dcd36_idx'), models.Index(fields=['tipo_acao', '-criado_em'], name='gestao_rura_tipo_ac_107ca8_idx'), models.Index(fields=['ip_address', '-criado_em'], name='gestao_rura_ip_addr_95a29d_idx')],
            },
        ),
    ]
