# Generated by Django 4.2.7 on 2025-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0047_add_tipo_registro_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='curralsessao',
            name='nome_lote',
            field=models.CharField(blank=True, help_text='Nome do lote que será trabalhado', max_length=100, null=True, verbose_name='Nome do Lote'),
        ),
        migrations.AddField(
            model_name='curralsessao',
            name='pasto_origem',
            field=models.CharField(blank=True, help_text='Pasto de origem dos animais', max_length=200, null=True, verbose_name='Pasto de Origem'),
        ),
        migrations.AddField(
            model_name='curralsessao',
            name='quantidade_esperada',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de animais esperada para este trabalho', null=True, verbose_name='Quantidade Esperada'),
        ),
        migrations.AddField(
            model_name='curralsessao',
            name='tipo_trabalho',
            field=models.CharField(choices=[('INVENTARIO', 'Inventário de Animais'), ('CONFERENCIA', 'Conferência'), ('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('COLETA_DADOS', 'Coleta de Dados')], default='COLETA_DADOS', help_text='Tipo de trabalho que será realizado nesta sessão', max_length=20, verbose_name='Tipo de Trabalho'),
        ),
    ]
