# Generated by Django 4.2.7 on 2025-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0048_curralsessao_nome_lote_curralsessao_pasto_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curralsessao',
            name='tipo_trabalho',
            field=models.CharField(choices=[('PESAGEM_ROTINA', 'Pesagem de Rotina'), ('VENDA_FRIGORIFICO', 'Venda para Frigorífico'), ('VENDA_TERCEIROS', 'Venda Para Terceiros'), ('IATF', 'IATF'), ('INVENTARIO', 'Inventário de Animais'), ('CONFERENCIA', 'Conferência'), ('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('COLETA_DADOS', 'Coleta de Dados'), ('OUTROS', 'Outros')], default='COLETA_DADOS', help_text='Tipo de trabalho que será realizado nesta sessão', max_length=20, verbose_name='Tipo de Trabalho'),
        ),
    ]
