# Generated by Django 4.2.7 on 2025-11-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0049_alter_curralsessao_tipo_trabalho'),
        ('gestao_rural', '0050_adicionar_campos_timestamp_categoriafinanceira'),
    ]

    operations = [
    ]
