# Generated by Django 4.2.7 on 2025-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0051_merge_20251122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoprojetada',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('NASCIMENTO', 'Nascimento'), ('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('MORTE', 'Morte'), ('TRANSFERENCIA_ENTRADA', 'Transferência de Entrada'), ('TRANSFERENCIA_SAIDA', 'Transferência de Saída'), ('PROMOCAO_ENTRADA', 'Promoção de Entrada (Evolução de Idade)'), ('PROMOCAO_SAIDA', 'Promoção de Saída (Evolução de Idade)')], max_length=25, verbose_name='Tipo de Movimentação'),
        ),
    ]
