# Generated by Django 4.2.7 on 2025-11-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0052_adicionar_tipos_promocao_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
