# Generated by Django 4.2.7 on 2025-11-26 20:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0053_propriedade_inscricao_estadual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoCEPEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('ano', models.PositiveIntegerField(db_index=True, verbose_name='Ano')),
                ('tipo_categoria', models.CharField(choices=[('BEZERRO', 'Bezerro (0-12 meses)'), ('BEZERRA', 'Bezerra (0-12 meses)'), ('GARROTE', 'Garrote (12-24 meses)'), ('NOVILHA', 'Novilha (12-24 meses)'), ('BOI', 'Boi (24-36 meses)'), ('BOI_MAGRO', 'Boi Magro (24-36 meses)'), ('PRIMIPARA', 'Primípara (24-36 meses)'), ('MULTIPARA', 'Multípara (>36 meses)'), ('VACA_DESCARTE', 'Vaca Descarte (>36 meses)'), ('TOURO', 'Touro (>36 meses)')], db_index=True, max_length=20, verbose_name='Tipo de Categoria')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Médio (R$/cabeça)')),
                ('preco_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Mínimo (R$/cabeça)')),
                ('preco_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Máximo (R$/cabeça)')),
                ('fonte', models.CharField(default='CEPEA', max_length=100, verbose_name='Fonte dos Dados')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Preço CEPEA',
                'verbose_name_plural': 'Preços CEPEA',
                'ordering': ['-ano', 'uf', 'tipo_categoria'],
                'indexes': [models.Index(fields=['uf', 'ano'], name='gestao_rura_uf_5707a6_idx'), models.Index(fields=['tipo_categoria', 'ano'], name='gestao_rura_tipo_ca_f2e3c0_idx')],
                'unique_together': {('uf', 'ano', 'tipo_categoria')},
            },
        ),
    ]
