# Generated by Django 4.2.7 on 2025-11-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0054_adicionar_preco_cepea'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro/Distrito'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='ponto_referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Ponto de Referência'),
        ),
    ]
