# Generated by Django 4.2.7 on 2025-11-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0055_propriedade_bairro_propriedade_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaProjetada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('cliente_nome', models.CharField(blank=True, help_text='Nome do cliente da venda (será vinculado ao cadastro quando disponível)', max_length=200, null=True, verbose_name='Nome do Cliente')),
                ('peso_total_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Total (kg)')),
                ('peso_medio_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Médio por Animal (kg)')),
                ('valor_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por KG (R$)')),
                ('valor_por_animal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por Animal (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('prazo_pagamento_dias', models.PositiveIntegerField(default=30, verbose_name='Prazo de Pagamento (dias)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.categoriaanimal', verbose_name='Categoria')),
                ('cenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_projetadas', to='gestao_rural.cenarioplanejamento', verbose_name='Cenário')),
                ('movimentacao_projetada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_geradas', to='gestao_rural.movimentacaoprojetada', verbose_name='Movimentação Projetada Origem')),
                ('planejamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_projetadas', to='gestao_rural.planejamentoanual', verbose_name='Planejamento Anual')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_projetadas', to='gestao_rural.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Venda Projetada',
                'verbose_name_plural': 'Vendas Projetadas',
                'ordering': ['-data_venda', 'categoria'],
                'indexes': [models.Index(fields=['propriedade', 'data_venda'], name='gestao_rura_proprie_d5e843_idx'), models.Index(fields=['cenario', 'data_venda'], name='gestao_rura_cenario_6351dd_idx'), models.Index(fields=['cliente_nome', 'data_venda'], name='gestao_rura_cliente_315ee3_idx')],
            },
        ),
    ]
