# Generated by Django 4.2.7 on 2025-11-26 22:27

from django.db import migrations, models


def gerar_codigos_planejamentos_existentes(apps, schema_editor):
    """Gera códigos únicos para planejamentos existentes"""
    PlanejamentoAnual = apps.get_model('gestao_rural', 'PlanejamentoAnual')
    
    # Agrupar por ano e gerar códigos sequenciais
    planejamentos = PlanejamentoAnual.objects.filter(codigo__isnull=True).order_by('ano', 'data_criacao')
    
    codigos_por_ano = {}
    
    for planejamento in planejamentos:
        ano = planejamento.ano
        
        if ano not in codigos_por_ano:
            # Buscar o último código do mesmo ano
            ultimo_planejamento = PlanejamentoAnual.objects.filter(
                ano=ano,
                codigo__isnull=False
            ).exclude(id=planejamento.id).order_by('-codigo').first()
            
            if ultimo_planejamento and ultimo_planejamento.codigo:
                try:
                    partes = ultimo_planejamento.codigo.split('-')
                    if len(partes) == 3 and partes[0] == 'PROJ':
                        codigos_por_ano[ano] = int(partes[2])
                    else:
                        codigos_por_ano[ano] = 0
                except (ValueError, IndexError):
                    codigos_por_ano[ano] = 0
            else:
                codigos_por_ano[ano] = 0
        
        codigos_por_ano[ano] += 1
        planejamento.codigo = f"PROJ-{ano}-{codigos_por_ano[ano]:04d}"
        planejamento.save(update_fields=['codigo'])


def reverter_codigos_planejamentos(apps, schema_editor):
    """Remove códigos dos planejamentos (não necessário, mas implementado para reversão)"""
    PlanejamentoAnual = apps.get_model('gestao_rural', 'PlanejamentoAnual')
    PlanejamentoAnual.objects.all().update(codigo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0056_vendaprojetada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentoanual',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único identificador da projeção (gerado automaticamente)', max_length=20, null=True, unique=True, verbose_name='Código da Projeção'),
        ),
        migrations.RunPython(
            gerar_codigos_planejamentos_existentes,
            reverse_code=reverter_codigos_planejamentos
        ),
        migrations.AddIndex(
            model_name='planejamentoanual',
            index=models.Index(fields=['codigo'], name='gestao_rura_codigo_ea26b1_idx'),
        ),
        migrations.AddIndex(
            model_name='planejamentoanual',
            index=models.Index(fields=['ano', 'propriedade'], name='gestao_rura_ano_2dbe66_idx'),
        ),
    ]
