# Generated by Django 4.2.7 on 2025-11-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0058_cliente_fornecedorcadastro_frigorifico_unidademedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetobancario',
            name='planejamento',
            field=models.ForeignKey(blank=True, help_text='Vincule a um planejamento anual para avaliar cenários de projeção no projeto bancário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_bancarios', to='gestao_rural.planejamentoanual', verbose_name='Planejamento de Projeção'),
        ),
    ]
