# Generated by Django 4.2.7 on 2025-11-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0060_adicionar_campo_banco_contafinanceira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamentoanual',
            options={'ordering': ['-data_criacao', '-ano', 'propriedade'], 'verbose_name': 'Planejamento Anual Pecuário', 'verbose_name_plural': 'Planejamentos Anuais Pecuários'},
        ),
        migrations.AlterUniqueTogether(
            name='planejamentoanual',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='planejamentoanual',
            index=models.Index(fields=['data_criacao'], name='gestao_rura_data_cr_83ae62_idx'),
        ),
    ]
