# Generated by Django 4.2.7 on 2025-11-27 13:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0061_remover_unique_together_planejamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Grupo')),
                ('tipo', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_despesa', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Grupo de Despesa',
                'verbose_name_plural': 'Grupos de Despesas',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('propriedade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='DespesaConfigurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Despesa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_calculo', models.CharField(choices=[('PORCENTAGEM', 'Porcentagem sobre Receita'), ('VALOR_FIXO_MENSAL', 'Valor Fixo Mensal'), ('VALOR_FIXO_ANUAL', 'Valor Fixo Anual')], default='PORCENTAGEM', max_length=20, verbose_name='Tipo de Cálculo')),
                ('porcentagem_receita', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual da receita anual que será destinado a esta despesa.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentagem sobre Receita (%)')),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo mensal ou anual, dependendo do tipo de cálculo.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Fixo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('categoria_financeira', models.ForeignKey(limit_choices_to={'tipo': 'DESPESA'}, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_configuradas', to='gestao_rural.categoriafinanceira')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='gestao_rural.grupodespesa')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_configuradas', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Despesa Configurada',
                'verbose_name_plural': 'Despesas Configuradas',
                'ordering': ['grupo__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ReceitaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('valor_receita', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da Receita (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Observações')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_anuais', to='gestao_rural.propriedade')),
            ],
            options={
                'verbose_name': 'Receita Anual',
                'verbose_name_plural': 'Receitas Anuais',
                'ordering': ['-ano'],
                'unique_together': {('propriedade', 'ano')},
            },
        ),
    ]
