# Generated by Django 4.2.7 on 2025-11-27 11:10

from django.db import migrations


def adicionar_campo_agencia_se_nao_existir(apps, schema_editor):
    """Adiciona o campo agencia se ele não existir na tabela."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar se a coluna já existe
        cursor.execute("""
            SELECT COUNT(*) FROM pragma_table_info('gestao_rural_contafinanceira') 
            WHERE name='agencia'
        """)
        existe = cursor.fetchone()[0] > 0
        
        if not existe:
            # Adicionar a coluna se não existir
            cursor.execute("""
                ALTER TABLE gestao_rural_contafinanceira 
                ADD COLUMN agencia VARCHAR(20) DEFAULT ''
            """)


def remover_campo_agencia_se_existir(apps, schema_editor):
    """Remove o campo agencia se ele existir (para rollback)."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar se a coluna existe
        cursor.execute("""
            SELECT COUNT(*) FROM pragma_table_info('gestao_rural_contafinanceira') 
            WHERE name='agencia'
        """)
        existe = cursor.fetchone()[0] > 0
        
        if existe:
            # Em produção, isso precisaria de uma estratégia diferente
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0062_adicionar_grupos_despesas_receitas_anuais'),
    ]

    operations = [
        migrations.RunPython(
            adicionar_campo_agencia_se_nao_existir,
            reverse_code=remover_campo_agencia_se_existir,
        ),
    ]














