# Generated by Django 4.2.7 on 2025-11-27 15:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0064_adicionar_campo_permite_negativo_contafinanceira'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitaanual',
            name='abatimentos_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Abatimentos sobre Vendas (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='custo_produtos_vendidos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo direto dos produtos/mercadorias vendidas', max_digits=14, verbose_name='Custo dos Produtos Vendidos - CPV (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='depreciacao_amortizacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Depreciação e Amortização (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_financeiras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Juros, taxas bancárias, etc.', max_digits=14, verbose_name='Despesas Financeiras (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='devolucoes_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Devoluções de Vendas (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='imposto_renda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Imposto de Renda e Contribuição Social (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='impostos_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ICMS, PIS, COFINS, etc.', max_digits=14, verbose_name='Impostos sobre Vendas (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='receitas_financeiras',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aplicações financeiras, rendimentos, etc.', max_digits=14, verbose_name='Receitas Financeiras (R$)'),
        ),
        migrations.AlterField(
            model_name='receitaanual',
            name='valor_receita',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Receita bruta antes de deduções', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da Receita Bruta (R$)'),
        ),
    ]
