# Generated by Django 4.2.7 on 2025-11-27 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0065_adicionar_campos_dre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitaanual',
            name='imposto_renda',
        ),
        migrations.RemoveField(
            model_name='receitaanual',
            name='impostos_vendas',
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='csll',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Contribuição Social sobre Lucro Líquido - CSLL (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='funviral_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Funviral sobre Vendas (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='icms_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ICMS sobre Vendas (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='irpj',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Imposto de Renda Pessoa Jurídica - IRPJ (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='outros_impostos_vendas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PIS, COFINS, etc.', max_digits=14, verbose_name='Outros Impostos sobre Vendas (R$)'),
        ),
    ]
