# Generated by Django 4.2.7 on 2025-11-27 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0066_ajustar_campos_dre_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitaanual',
            name='assistencia_contabil',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Assistência Contábil (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_administrativas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Administrativas (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_combustivel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Combustível (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_comunicacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Comunicação (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_energia_eletrica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Energia Elétrica (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_manutencao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Manutenção (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_transportes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Transportes (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='despesas_viagens',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Despesas Viagens (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='encargos_inss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Encargos INSS (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='material_uso_consumo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Material de Uso e Consumo (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='retirada_labore',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retirada de pró-labore dos sócios', max_digits=14, verbose_name='Retirada Labore (R$)'),
        ),
        migrations.AddField(
            model_name='receitaanual',
            name='taxas_diversas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Taxas Diversas (R$)'),
        ),
    ]
