# Generated by Django 4.2.7 on 2025-12-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0067_adicionar_despesas_operacionais_detalhadas'),
    ]

    operations = [
        # Migration placeholder - arquivo criado para corrigir erro de migração ausente
        # Esta migração não realiza alterações no banco de dados
    ]











