# Generated by Django 4.2.7 on 2025-12-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0069_adicionar_status_bnd_animal'),
        ('gestao_rural', '0073_adicionar_campos_obrigatorios_nfe_item'),
    ]

    operations = [
    ]
