# Generated by Django 4.2.7 on 2025-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0078_arquivokml_folhapagamento_funcionario_pastagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturacliente',
            name='data_liberacao',
            field=models.DateField(blank=True, help_text='Data a partir da qual o usuário terá acesso ao sistema. Se não definida, o acesso será imediato após pagamento confirmado.', null=True, verbose_name='Data de Liberação'),
        ),
    ]
