# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0082_produtorrural_certificado_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, help_text='Justificativa obrigatória para cancelamento da NF-e (mínimo 15 caracteres)', null=True, verbose_name='Justificativa do Cancelamento'),
        ),
    ]






