# Generated by Django 4.2.7 on 2025-12-29 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remove_unique_together_safely(apps, schema_editor):
    """Remove unique_together de forma segura, ignorando se o índice não existir"""
    db_alias = schema_editor.connection.alias
    db_vendor = schema_editor.connection.vendor
    SetorPropriedade = apps.get_model('gestao_rural', 'SetorPropriedade')
    
    # Tentar remover o unique_together usando SQL direto
    with schema_editor.connection.cursor() as cursor:
        index_exists = False
        if db_vendor == 'postgresql':
            # Verificar se o índice existe no PostgreSQL
            cursor.execute("""
                SELECT COUNT(*) FROM pg_indexes 
                WHERE indexname='unique_setor_por_propriedade_nome'
            """)
            index_exists = cursor.fetchone()[0] > 0
        else:  # SQLite
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name='unique_setor_por_propriedade_nome'
            """)
            index_exists = cursor.fetchone() is not None
        
        if index_exists:
            # Índice existe, tentar removê-lo
            try:
                cursor.execute("DROP INDEX IF EXISTS unique_setor_por_propriedade_nome")
            except Exception:
                # Se falhar, não é crítico - o índice pode já ter sido removido
                pass


def reverse_remove_unique_together(apps, schema_editor):
    """Operação reversa - não faz nada pois não podemos recriar o índice facilmente"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0088_add_preferencia_modulos_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('objetivo_principal', models.TextField(help_text='Qual o objetivo principal desta campanha?')),
                ('publico_alvo', models.TextField(help_text='Descrição do público-alvo')),
                ('meta_leads', models.IntegerField(default=0)),
                ('meta_conversoes', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campanha de Marketing',
                'verbose_name_plural': 'Campanhas de Marketing',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_site', models.URLField(default='https://monpec.com.br', help_text='URL principal do site')),
                ('url_whatsapp', models.CharField(default='', help_text='Número do WhatsApp (formato: 5511999999999)', max_length=50)),
                ('email_contato', models.EmailField(default='contato@monpec.com.br', max_length=254)),
                ('mensagem_cta_padrao', models.TextField(default='👉 Entre em contato e descubra como o MONPEC pode transformar sua gestão!', help_text='Call-to-action padrão para posts')),
                ('variaveis_padrao', models.JSONField(default=dict, help_text='Variáveis padrão usadas na geração de posts (JSON)')),
                ('ativar_acesso_gratuito', models.BooleanField(default=True, help_text='Ativar oferta de acesso gratuito na landing page')),
                ('mensagem_acesso_gratuito', models.TextField(default='Acesse gratuitamente o MONPEC e descubra como transformar sua gestão rural!', help_text='Mensagem de acesso gratuito')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Marketing',
                'verbose_name_plural': 'Configurações de Marketing',
            },
        ),
        migrations.CreateModel(
            name='LeadInteressado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('propriedade_nome', models.CharField(blank=True, help_text='Nome da propriedade/fazenda', max_length=200)),
                ('tipo_atividade', models.CharField(blank=True, choices=[('pecuaria_corte', 'Pecuária de Corte'), ('pecuaria_leite', 'Pecuária de Leite'), ('agricultura', 'Agricultura'), ('outro', 'Outro')], max_length=100)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], default='novo', max_length=50)),
                ('origem', models.CharField(default='landing_page', help_text='De onde veio o lead', max_length=100)),
                ('credenciais_enviadas', models.BooleanField(default=False)),
                ('credenciais_enviadas_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Interessado',
                'verbose_name_plural': 'Leads Interessados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PostGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo_final', models.TextField(help_text='Conteúdo do post já processado (sem variáveis)')),
                ('hashtags_final', models.CharField(blank=True, max_length=500)),
                ('rede_social', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('geral', 'Geral (Todas)')], max_length=50)),
                ('tipo_post', models.CharField(choices=[('apresentacao', 'Apresentação'), ('problema_solucao', 'Problema x Solução'), ('funcionalidade', 'Funcionalidade'), ('prova_social', 'Prova Social'), ('educacao', 'Educação/Dica'), ('vendas', 'Vendas/Oferta'), ('engajamento', 'Engajamento'), ('humanizacao', 'Humanização'), ('tendencias', 'Tendências')], max_length=50)),
                ('variaveis_usadas', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=50)),
                ('agendar_para', models.DateTimeField(blank=True, help_text='Agendar publicação para data/hora específica', null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('engajamento', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Gerado',
                'verbose_name_plural': 'Posts Gerados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador do template', max_length=200)),
                ('tipo_post', models.CharField(choices=[('apresentacao', 'Apresentação'), ('problema_solucao', 'Problema x Solução'), ('funcionalidade', 'Funcionalidade'), ('prova_social', 'Prova Social'), ('educacao', 'Educação/Dica'), ('vendas', 'Vendas/Oferta'), ('engajamento', 'Engajamento'), ('humanizacao', 'Humanização'), ('tendencias', 'Tendências')], max_length=50)),
                ('rede_social', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('geral', 'Geral (Todas)')], default='geral', max_length=50)),
                ('conteudo', models.TextField(help_text='Conteúdo do post com variáveis entre chaves {variavel}')),
                ('hashtags', models.TextField(blank=True, help_text='Hashtags separadas por vírgula')),
                ('variaveis_disponiveis', models.JSONField(blank=True, default=dict, help_text='Variáveis que podem ser usadas no template (JSON)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Post',
                'verbose_name_plural': 'Templates de Posts',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='autorizacaoexcedenteorcamento',
            options={'verbose_name': 'Autorização de Excedente de Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='eventofluxocompra',
            options={'verbose_name': 'Evento de Fluxo de Compra'},
        ),
        migrations.AlterModelOptions(
            name='itemordemcompra',
            options={'verbose_name': 'Item de Ordem de Compra', 'verbose_name_plural': 'Itens de Ordem de Compra'},
        ),
        migrations.AlterModelOptions(
            name='ordemcompra',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Ordem de Compra', 'verbose_name_plural': 'Ordens de Compra'},
        ),
        migrations.AlterModelOptions(
            name='preferenciamodulosusuario',
            options={'ordering': ['-atualizado_em'], 'verbose_name': 'Preferência de Módulos do Usuário', 'verbose_name_plural': 'Preferências de Módulos dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='setorpropriedade',
            options={'verbose_name': 'Setor da Propriedade'},
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='gestao_rura_codigo_3ddda1_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='gestao_rura_ncm_051d9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='gestao_rura_ativo_27fe2b_idx',
        ),
        migrations.RenameIndex(
            model_name='documentopropriedade',
            new_name='gestao_rura_proprie_0b4368_idx',
            old_name='gestao_rur_proprie_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='documentopropriedade',
            new_name='gestao_rura_data_ve_c6de70_idx',
            old_name='gestao_rur_data_ve_12345_idx',
        ),
        migrations.RunPython(
            remove_unique_together_safely,
            reverse_remove_unique_together,
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='data_solicitacao',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='observacoes_aprovacao',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='ordem_compra',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='solicitado_por',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='valor_excedente',
        ),
        migrations.RemoveField(
            model_name='autorizacaoexcedenteorcamento',
            name='valor_total_compra',
        ),
        migrations.RemoveField(
            model_name='cotacaofornecedor',
            name='requisicao',
        ),
        migrations.RemoveField(
            model_name='eventofluxocompra',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='eventofluxocompra',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='eventofluxocompra',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='eventofluxocompra',
            name='status_anterior',
        ),
        migrations.RemoveField(
            model_name='eventofluxocompra',
            name='status_novo',
        ),
        migrations.RemoveField(
            model_name='eventofluxocompra',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='codigo_produto',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='quantidade_recebida',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='quantidade_solicitada',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='unidade_medida',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='itemordemcompra',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_sincronizacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm_data_validacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm_validado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sincronizado_receita',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='usuario_cadastro',
        ),
        migrations.RemoveField(
            model_name='requisicaocompra',
            name='numero',
        ),
        migrations.AddField(
            model_name='parametrosvendaporcategoria',
            name='preco_maximo_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Máximo por Kg (R$)'),
        ),
        migrations.AddField(
            model_name='parametrosvendaporcategoria',
            name='preco_medio_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Médio por Kg (R$)'),
        ),
        migrations.AddField(
            model_name='parametrosvendaporcategoria',
            name='preco_minimo_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Mínimo por Kg (R$)'),
        ),
        migrations.AlterField(
            model_name='ajusteorcamentocompra',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_orcamento_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='autorizacaoexcedenteorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.orcamentocompramensal'),
        ),
        migrations.AlterField(
            model_name='eventofluxocompra',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.requisicaocompra'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='conta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tipo',
            field=models.CharField(choices=[('RACAO', 'Ração/Insumos'), ('MEDICAMENTO', 'Medicamentos/Veterinário'), ('EQUIPAMENTO', 'Equipamentos'), ('COMBUSTIVEL', 'Combustível'), ('SERVICO', 'Serviços'), ('CONSTRUCAO', 'Construção'), ('TRANSPORTE', 'Transporte'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Fornecedor'),
        ),
        migrations.AlterField(
            model_name='itemordemcompra',
            name='ordem_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao_rural.ordemcompra'),
        ),
        migrations.AlterField(
            model_name='orcamentocompramensal',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compras_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='orcamentocompramensal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compras_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_rural.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_cofins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota ICMS (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_ipi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota IPI (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_pis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota PIS (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_rural.categoriaproduto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_entrada',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP Entrada'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_saida_estadual',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP Saída Estadual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_saida_interestadual',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP Saída Interestadual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_cofins',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CST COFINS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_icms',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CST ICMS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_ipi',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CST IPI'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_pis',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CST PIS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_completa',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ex_tipi',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Exceção da TIPI'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='GTIN/EAN'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm_descricao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição do NCM'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='origem_mercadoria',
            field=models.CharField(choices=[('0', '0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8'), ('1', '1 - Estrangeira - Importação direta, exceto a indicada no código 6'), ('2', '2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7'), ('3', '3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%'), ('4', '4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos'), ('5', '5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%'), ('6', '6 - Estrangeira - Importação direta, sem similar nacional'), ('7', '7 - Estrangeira - Adquirida no mercado interno, sem similar nacional'), ('8', '8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%')], default='0', max_length=1, verbose_name='Origem da Mercadoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de Custo (R$)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de Venda (R$)'),
        ),
        migrations.AlterField(
            model_name='setorpropriedade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setorpropriedade',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade'),
        ),
        migrations.AddField(
            model_name='postgerado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postgerado',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_rural.templatepost'),
        ),
        migrations.AddField(
            model_name='campanhamarketing',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='setorpropriedade',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='setorpropriedade',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='setorpropriedade',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='setorpropriedade',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='setorpropriedade',
            name='responsavel',
        ),
    ]
