# Generated by Django 4.2.7 on 2025-12-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0089_campanhamarketing_configuracaomarketing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setorpropriedade',
            unique_together=set(),
        ),
    ]
