# Generated by Django 4.2.7 on 2026-01-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_rural', '0100_otimizacoes_indices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='produtorrural',
            new_name='gestao_rura_usuario_f00e29_idx',
            old_name='gestao_rur_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='produtorrural',
            new_name='gestao_rura_cpf_cnp_c4cb6c_idx',
            old_name='gestao_rur_cpf_cnpj_idx',
        ),
        migrations.RenameIndex(
            model_name='produtorrural',
            new_name='gestao_rura_data_ca_68f6c7_idx',
            old_name='gestao_rur_data_cad_idx',
        ),
        migrations.RenameIndex(
            model_name='propriedade',
            new_name='gestao_rura_produto_bfe9ba_idx',
            old_name='gestao_rur_prod_nome_idx',
        ),
        migrations.RenameIndex(
            model_name='propriedade',
            new_name='gestao_rura_produto_3a2636_idx',
            old_name='gestao_rur_prod_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='propriedade',
            new_name='gestao_rura_data_ca_3a09f5_idx',
            old_name='gestao_rur_prop_data_idx',
        ),
    ]
