# Generated by Django 4.2.7 on 2026-01-10 04:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao_rural', '0106_remover_stripe_definitivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalindividual',
            name='data_cadastro_bnd',
            field=models.DateField(blank=True, help_text='Data em que o animal foi cadastrado no Banco Nacional de Dados (BND)', null=True, verbose_name='Data de Cadastro BND'),
        ),
        migrations.AddField(
            model_name='animalindividual',
            name='numero_registro_bnd',
            field=models.CharField(blank=True, help_text='Número do registro oficial no Banco Nacional de Dados (BND)', max_length=50, null=True, verbose_name='Número do Registro BND'),
        ),
        migrations.AlterField(
            model_name='ajusteorcamentocompra',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_orcamento_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='orcamentocompramensal',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compras_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='orcamentocompramensal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compras_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
