"""
Django settings for sistema_rural project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='True', cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# ✅ SEGURANÇA: SECRET_KEY deve sempre vir de variável de ambiente
# Usar config() do decouple primeiro, mas fazer fallback para os.getenv() 
# para garantir compatibilidade com Cloud Run e outros ambientes sem arquivo .env
SECRET_KEY = config('SECRET_KEY', default=None)
if not SECRET_KEY:
    # Fallback para variável de ambiente do sistema (necessário para Cloud Run)
    SECRET_KEY = os.getenv('SECRET_KEY')
    
if not SECRET_KEY:
    if DEBUG:
        # Em desenvolvimento, usar chave temporária (NUNCA em produção)
        import warnings
        warnings.warn(
            "SECRET_KEY não configurada! Usando chave temporária apenas para desenvolvimento. "
            "Configure SECRET_KEY no arquivo .env para evitar este aviso.",
            UserWarning
        )
        SECRET_KEY = 'YrJOs823th_HB2BP6Uz9A0NVvzL0Fif-t-Rfub5BXgVtE0LxXIWEPQIFqYvI8UNiZKE'
    else:
        raise ValueError(
            "SECRET_KEY não configurada! Configure a variável de ambiente SECRET_KEY antes de executar em produção."
        )

ALLOWED_HOSTS = [
       'localhost',
       '127.0.0.1',
       '192.168.100.4',  # IP do seu PC na rede Wi-Fi
       '192.168.100.91',  # IP atual do servidor na rede local
       '0.0.0.0',  # Permite acesso de qualquer IP na rede local
       'monpec.com.br',  # Domínio de produção
       'www.monpec.com.br',  # Domínio de produção com www
   ]

# Configuração CSRF para aceitar requisições do celular na rede local
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.100.4:8000',
    'http://192.168.100.91:8000',
    'https://monpec.com.br',  # Domínio de produção
    'https://www.monpec.com.br',  # Domínio de produção com www
    'http://monpec.com.br',  # Domínio de produção (HTTP)
    'http://www.monpec.com.br',  # Domínio de produção com www (HTTP)
]

# Configurações Mercado Pago
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='')
MERCADOPAGO_PUBLIC_KEY = config('MERCADOPAGO_PUBLIC_KEY', default='')
MERCADOPAGO_WEBHOOK_SECRET = config('MERCADOPAGO_WEBHOOK_SECRET', default='')
MERCADOPAGO_SUCCESS_URL = config('MERCADOPAGO_SUCCESS_URL', default='http://localhost:8000/assinaturas/sucesso/')
MERCADOPAGO_CANCEL_URL = config('MERCADOPAGO_CANCEL_URL', default='http://localhost:8000/assinaturas/cancelado/')

# Gateway de pagamento padrão (stripe, mercadopago, asaas, etc.)
PAYMENT_GATEWAY_DEFAULT = config('PAYMENT_GATEWAY_DEFAULT', default='mercadopago')

TENANT_DATABASE_DIR = Path(os.getenv('TENANT_DATABASE_DIR', str(BASE_DIR / 'tenants')))
TENANT_DATABASE_DIR.mkdir(parents=True, exist_ok=True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Sitemap para SEO
    'django.contrib.humanize',
    'gestao_rural.apps.GestaoRuralConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'gestao_rural.middleware_security.RateLimitMiddleware',  # Rate limiting
    'gestao_rural.middleware_protecao_codigo.ProtecaoCodigoMiddleware',  # Proteção contra cópia
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Deve vir ANTES dos middlewares que usam messages
    'gestao_rural.middleware_liberacao_acesso.LiberacaoAcessoMiddleware',  # Controle de liberação de acesso
    'gestao_rural.middleware_seguranca_avancada.SegurancaAvancadaMiddleware',  # Segurança avançada
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gestao_rural.middleware_security.SecurityHeadersMiddleware',  # Headers de segurança
    'gestao_rural.middleware_demo_protecao.DemoProtecaoMonpec1Middleware',  # Proteção Monpec1 para usuários demo
    'gestao_rural.middleware_demo.DemoRestrictionMiddleware',  # Restrição de demo (deve ser o último)
]

ROOT_URLCONF = 'sistema_rural.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'gestao_rural.context_processors.demo_mode',  # Adiciona DEMO_MODE ao contexto
                'gestao_rural.context_processors.assinatura_info',  # Adiciona informações de assinatura
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_rural.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Mínimo de 12 caracteres
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing_page'

# Configuração de E-mail (para recuperação de senha, convites de cotação e envio de NF-e)
# Configuração padrão temporária - cada usuário pode configurar o seu próprio via variáveis de ambiente
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# E-mail padrão configurado - pode ser sobrescrito por variáveis de ambiente
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='l.moncaosilva@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')  # Deve ser configurado via variável de ambiente ou .env
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='l.moncaosilva@gmail.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Configuração de Backup
BACKUP_DIR = Path(os.getenv('BACKUP_DIR', str(BASE_DIR / 'backups')))
BACKUP_DIR.mkdir(parents=True, exist_ok=True)

# URL do site (para links em e-mails)
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Link do grupo WhatsApp para demonstração
WHATSAPP_GRUPO_DEMO_LINK = config('WHATSAPP_GRUPO_DEMO_LINK', default='https://chat.whatsapp.com/SEU_LINK_DO_GRUPO_AQUI')

# ========================================
# CONFIGURAÇÕES DE DEMONSTRAÇÃO
# ========================================
# Ativar modo demo (True) ou desativar (False)
DEMO_MODE = os.getenv('DEMO_MODE', 'False').lower() == 'true'  # DESATIVADO - Versão completa

# Link para página de pagamento/assinatura
DEMO_LINK_PAGAMENTO = os.getenv('DEMO_LINK_PAGAMENTO', 'http://localhost:8000/assinaturas/')

# ========================================
# CONFIGURAÇÕES DO GOOGLE ANALYTICS
# ========================================
# ID de medição do Google Analytics (ex: G-XXXXXXXXXX)
GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID', '')

# ========================================
# CONFIGURAÇÕES DE PAGAMENTO
# ========================================
# CONFIGURAÇÕES DE SEGURANÇA
# ========================================
# Token para validação de webhooks WhatsApp
WHATSAPP_WEBHOOK_TOKEN = os.getenv('WHATSAPP_WEBHOOK_TOKEN', '')

# Configurações de segurança HTTPS/SSL (apenas em produção)
# Em desenvolvimento, deixar False para facilitar testes locais
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Em desenvolvimento, manter False para não bloquear HTTP local
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

