# Generated by Django 4.2.7 on 2025-10-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produtor Rural',
                'verbose_name_plural': 'Produtores Rurais',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('propria', 'Própria'), ('arrendada', 'Arrendada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.produtorrural')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioRebanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inventario', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_rural.categoriaanimal')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qt_parcelas', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='CustoVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('custo_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='CicloProducaoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('safra', models.CharField(max_length=20)),
                ('area_plantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtividade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receita_esperada_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='BemImobilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_aquisicao', models.DateField()),
                ('deprec_anual', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_rural.propriedade')),
            ],
        ),
    ]
